"""add indexes on country and age

Revision ID: 04a1dbd817ca
Revises: d40f4c348b4d
Create Date: 2026-06-16 14:49:52.415603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04a1dbd817ca'
down_revision: Union[str, Sequence[str], None] = 'd40f4c348b4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_age'), 'users', ['age'], unique=False)
    op.create_index(op.f('ix_users_country'), 'users', ['country'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_country'), table_name='users')
    op.drop_index(op.f('ix_users_age'), table_name='users')
    # ### end Alembic commands ###
