"""remove is_native

Revision ID: 57d25cfcd577
Revises: e31ba16e40b6
Create Date: 2026-06-02 17:59:16.236641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57d25cfcd577'
down_revision: Union[str, Sequence[str], None] = 'e31ba16e40b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_languages', 'level',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('user_languages', 'is_native')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_languages', sa.Column('is_native', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('user_languages', 'level',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
