"""add user sex

Revision ID: 85b4f8a24405
Revises: 04a1dbd817ca
Create Date: 2026-06-16 17:37:34.199164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85b4f8a24405'
down_revision: Union[str, Sequence[str], None] = '04a1dbd817ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sex', sa.String(length=10), nullable=False,
                                     server_default="other"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sex')
    # ### end Alembic commands ###
