"""add is_verified

Revision ID: 9f5baa1fc50c
Revises: 57d25cfcd577
Create Date: 2026-06-03 19:00:31.145862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f5baa1fc50c'
down_revision: Union[str, Sequence[str], None] = '57d25cfcd577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column(
        'is_verified', sa.Boolean(), nullable=False, server_default=sa.false())
                  )
    op.alter_column("users", "is_verified", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
