"""add name

Revision ID: d40f4c348b4d
Revises: 9f5baa1fc50c
Create Date: 2026-06-12 20:13:11.116247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd40f4c348b4d'
down_revision: Union[str, Sequence[str], None] = '9f5baa1fc50c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column(
        'name', sa.String(length=50), nullable=False, server_default=sa.false())
                  )
    op.alter_column("users", "name", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
